version: "3"
services:
  flask:
    image: flask
    ports:
      - "80:5000"
    networks:
      - flasknet
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "12345678"
    ports:
      - "5432:5432"
networks:
  flasknet:
